# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3f130a89219b009840b1604715f5294e"
application_url = "https://show-joshua-clubs-mens.trycloudflare.com"
embedded = true
name = "app"
handle = "app-1521"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts"

[auth]
redirect_urls = [
  "https://show-joshua-clubs-mens.trycloudflare.com/auth/callback",
  "https://show-joshua-clubs-mens.trycloudflare.com/auth/shopify/callback",
  "https://show-joshua-clubs-mens.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "zohaibalishah.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
